### PR TITLE
Fix max call stack error on bad input

### LINKED ISSUE #104: Max call stack size error on a certain input
Originally reported at https://github.com/mapbox/mapbox-gl-js/issues/6086#issuecomment-394814754

Minimal test case for Node v8:

```js
const geojsonvt = require('geojson-vt');

const coords = [];
for (let i = 0; i < 1400; i++) {
    coords.push([0.0, 0.0], [1.0, 0.0], [1.0, 1.0], [0.0, 1.0]);
}

const data = {
    "type": "LineString",
    "coordinates": coords
};

geojsonvt(data);
```

cc @JamesChevalier

### PR DESCRIPTION
**Pull request by mourner**
Closes #104 by eliminating recursion in the `simplify` routine.

### CODE REVIEW

**Comment by mourner** [comment]
This seems to severely hit simplification performance, so looking now whether we could optimize it...

**Comment by mourner** [comment]
I couldn't make non-recursive version fast enough (it was 27% slower), so I pushed an alternative fix which should hypothetically work, and fixes the sample above, but I'm not entirely sure, so would appreciate a review.

Basically the issue here is on a certain degenerate input, recursive simplification can go too deep because the "pivot" (the most distance point in the Douglas-Peucker simplification step) will be close to the left point all the time, so on every recursi ve call, the amount of points remaining for simplification will only be reduced by a small constant number. So the alternative fix I come up with is, if there are many pivot candidates equally distant from the current segment, we choose the one with index closest to the middle. That way if the input is degenerate and there are many pivot candidates, we'll split the recursion equally so that the call stack size is closer to log(n) than n.

@anandthakker could you take a look? Let me know if the above doesn't make sense and I'll try to clarify, it's a tricky issue.

**Comment by mourner** [comment]
@anandthakker good point, updated the comment.

**Comment by mourner** [comment]
In theory, this fix doesn't need to be ported to C++ because it doesn't have such harsh max call stack limit as JS, which varies depending on platform but is pretty low everywhere, e.g. ~10k on Chrome. But I'm not sure — @kkaefer thoughts?

**Comment by kkaefer** [comment]
Let's port this to C++ too; 10k stack calls aren't something we'd really want on the C++ side either.

**Pull request merged**
