### PR TITLE
Fix support for -540 / 540 lng

### PR DESCRIPTION
**Pull request by mcwhittemore**
This solves the error @davidtheclark mentioned in https://github.com/mapbox/mapbox-gl-js/issues/2912.

It also creates a failing test for a point far from the normal -360/360 world.

@mourner I'm pretty sure what needs to be done to get the 'far away world' points to work is to expand the `left` and `right` buckets to capture more than a single world. Does that sound right? Do you have other thoughts on how we can handle this?

I'm using the term world because that is how we've been talking about it in the [mapbox-gl-draw issue](https://github.com/mapbox/mapbox-gl-draw/issues/458#issuecomment-235783231) related to this problem. If you have a better term that would be great.

### CODE REVIEW

**Comment by mourner** [comment]
I'm not sure we should support data with coordinates more than 1 world away from the center world. It's tricky to fix and not worth it IMO.

**Comment by mcwhittemore** [comment]
@mourner are you saying you want to limit this to handling features between -540 and 540?

**Comment by mourner** [comment]
@mcwhittemore yes.

**Comment by mcwhittemore** [comment]
@mourner ok, changed this to just check the 3 world limits along with fixing the bug I linked too above.

**Comment by mourner** [comment]
@mcwhittemore looks good. Before we can merge, let's fix indentation in the new test (causes build failure currently), and rename it to `test-multi-world.js` so that it fits the established convention.

**Pull request merged**
